apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    tier: myapp
spec:
  selector:
    matchLabels:
      app: myapp-nginx
  replicas: 3
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp-nginx
        type: front-end
    spec:
      containers:
        - name: nginx
          image: nginx